name: CMake Build with Cache

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache apt packages
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/apt
            /var/lib/apt/lists
          key: apt-cache-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            apt-cache-${{ runner.os }}-

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake clang

      - name: Cache CMake build
        uses: actions/cache@v4
        with:
          path: build
          key: build-cache-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt', '**/*.cpp', '**/*.h') }}
          restore-keys: |
            build-cache-${{ runner.os }}-

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure

      - name: Run real Test
        working-directory: bin
        run: |
          prime -s 10k && prime -l 10k && prime -n 104729 && prime -i 10k
          && fibonacci -l 10 && fibonacci -i 100
