name: CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang libpng-dev libx11-dev

      - name: Cache CMake build
        uses: actions/cache@v4
        with:
          path: build
          key: build-cache-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt', '**/*.cpp', '**/*.h') }}
          restore-keys: |
            build-cache-${{ runner.os }}-

      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1
        with:
          vulkan_version: 1.4.309.0
          cache: true
          install_lavapipe: true  # optional software rasterizer

      - name: Build
        run: |
            echo "VULKAN_SDK=$VULKAN_SDK"
            cmake -S . -B build -DCMAKE_PREFIX_PATH="$VULKAN_SDK"
            cmake --build build

      - name: Run ctest
        working-directory: build
        run: ctest --output-on-failure
