name: CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake clang

      - name: Cache CMake build
        uses: actions/cache@v4
        with:
          path: build
          key: build-cache-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt', '**/*.cpp', '**/*.h') }}
          restore-keys: |
            build-cache-${{ runner.os }}
      - name: Install libpng
        run: sudo apt-get install -y libpng-dev

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run ctest
        working-directory: build
        run: ctest --output-on-failure
      - name: Run real Test
        working-directory: bin
        run: |
          echo "Running prime -s 100"
          ./prime -s 100
          echo "Running prime -l 100"
          ./prime -l 100
          echo "Running prime -n 104729"
          ./prime -n 104729
          echo "Running prime -i 1m"
          ./prime -i 1g
          echo "Running fibonacci -l 10"
          ./fibonacci -l 10
          echo "Running fibonacci -i 100"
          ./fibonacci -i 100
          echo "Running test_3d"
          ./test_3d
